name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-ios:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: xcodebuild test -scheme ViewToImage -destination 'platform=iOS Simulator,name=iPhone 16 Pro' CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

  test-macos:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Build and test
        run: xcodebuild test -scheme ViewToImage -destination 'platform=macOS,arch=x86_64'
